### ISSUE TITLE
route function generate url error

### ISSUE THREAD

**Issue by hooklife** [spatie/laravel-paginateroute#31] opened 2017-08-02 16:28 UTC
use 

`Route::get('video_list', 'Video\ListController@index')->name('video.list.index');`

`<a href="{{ route('video.list.index',['sort'=>'recorded_at-desc']) }}">new </a>`

result
`<a href="http://xxx.dev/video_list?sort=created_at-desc">new</a>`

---
use

`Route::paginate('video_list', 'Video\ListController@index')->name('video.list.index');`

`<a href="{{ route('video.list.index',['sort'=>'recorded_at-desc']) }}">new </a>`

result

 `<a href="http://xxx.dev/video_list/created_at-desc">new</a>`

i redirect to this url 404

**Comment by sebastiandedeyne** [comment] 2017-10-04 13:56
Duplicate of #21

**Closed as completed by sebastiandedeyne** 2017-10-04 13:56 UTC
